### ISSUE TITLE
EIDPWebAppCache logging fails when context is null

### ISSUE THREAD

**Issue by david-guzman** [UCL/EIDP#12]
```
[#|2015-06-23T16:24:52.593+0100|WARNING|glassfish3.1.2|javax.enterprise.system.container.ejb.com.sun.ejb.containers|_ThreadID=74;_ThreadName=Thread-2;|EJB5184:A system exception occurred during an invocation on 
EJB EIDPWebAppCache, method: public void com.eidp.webctrl.WebAppCache.EIDPWebAppCache.setApplicationContext(java.lang.String)|#]

Caused by: java.lang.NullPointerException
        at com.eidp.webctrl.WebAppCache.EIDPWebAppCacheLogger.createLogger(EIDPWebAppCacheLogger.java:30)
```

**Comment by david-guzman** [comment]
Exception is no longer thrown but triggers exception in DBMapping

```
java.lang.NullPointerException
        at com.eidp.core.DB.DBMapping.remove(DBMapping.java:682)
        at com.eidp.core.DB.DBMapping.sessionDestroyed(DBMapping.java:722)
        at org.apache.catalina.session.StandardSession.expire(StandardSession.java:807)
        at org.apache.catalina.session.StandardSession.expire(StandardSession.java:769)
        at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:686)
        at org.apache.catalina.session.StandardManager.processExpires(StandardManager.java:997)
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5779)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1793)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1782)
        at java.lang.Thread.run(Thread.java:745)
|#]
```
